# create base image
FROM node:alpine

WORKDIR '/app'

# install dependencies
COPY ./package.json ./
RUN npm install 
COPY . . 

# build
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html